#!/bin/bash
echo "Enter the Node number: "
read NODEID
echo "Enter the Domain: "
read DOMAIN
echo "Enter the CertMode: "
read CERT_MODE
apt-get update && upgrade -y
echo "root:ashkan" | sudo chpasswd
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
systemctl restart sshd
echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf
sudo apt install curl -y
sudo ufw disable
sudo apt install snapd -y
sudo snap install hello-world
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
echo 'y' | sudo certbot certonly --standalone --register-unsafely-without-email -d v$NODEID.$DOMAIN 
sudo certbot certonly --standalone -d t$NODEID.$DOMAIN -d s$NODEID.$DOMAIN
bash <(curl -Ls https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh)
sudo rm /etc/XrayR/config.yml
mv /ubuntu/config.yml /etc/XrayR/
sed -i 's/NodeID: 00/NodeID: $NODEID/g' /etc/XrayR/config.yml
sed -i 's/v00.test.xyz/v$NODEID.$DOMAIN/g' /etc/XrayR/config.yml
sed -i 's/t00.test.xyz/t$NODEID.$DOMAIN/config.yml
sed -i 's/s00.test.xyz/s$NODEID.$DOMAIN/config.yml
sed -i 's/CertMode: none/CertMode: $CERT_MODE/g' /etc/XrayR/config.yml
xrayr restart
xrayr status
