#!/bin/bash
#GetIPaddress
IP=$(curl -s ifconfig.me)
#GetNodeNumber
echo "Enter the Node number: "
read NODEID
#GetDomain
echo "Enter the Domain: "
read DOMAIN
#GetZone
echo "Enter the zone number"
read ZONE
apt-get update && upgrade -y
sudo apt install curl -y
#EditRecords
sed -i "s/zone_identifier/$ZONE/g" DNS.sh
sed -i "s/IP/$IP/g" DNS.sh
sed -i "s/NODEID/$NODEID/g" DNS.sh
bash DNS.sh
echo "root:Kontekasif0$" | sudo chpasswd
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
systemctl restart sshd
echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf
sudo ufw disable
bash <(curl -Ls https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh)
sudo rm /etc/XrayR/config.yml
mv config.yml /etc/XrayR/
sed -i "s/NodeID: 00/NodeID: $NODEID/g" /etc/XrayR/config.yml
sed -i "s/v00.test.xyz/v$NODEID.$DOMAIN/g" /etc/XrayR/config.yml
sed -i "s/t00.test.xyz/t$NODEID.$DOMAIN/g" /etc/XrayR/config.yml
sed -i "s/s00.test.xyz/s$NODEID.$DOMAIN/g" /etc/XrayR/config.yml
xrayr restart
xrayr status
