#!/bin/bash
#GetIPaddress
IP=$(curl -s ifconfig.me)
#GetNodeNumber
$1
#GetDomain
$2
#GetZone
$3
apt-get update && upgrade -y
sudo apt install curl -y
#EditRecords
sed -i "s/zone_identifier/$3/g" DNS.sh
sed -i "s/IP/$IP/g" DNS.sh
sed -i "s/NODEID/$1/g" DNS.sh
bash DNS.sh
echo "root:Kontekasif0$" | sudo chpasswd
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
systemctl restart sshd
echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf
sudo ufw disable
bash <(curl -Ls https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh)
sudo rm /etc/XrayR/config.yml
mv config.yml /etc/XrayR/
sed -i "s/NodeID: 00/NodeID: $1/g" /etc/XrayR/config.yml
sed -i "s/v00.test.xyz/v$1.$2/g" /etc/XrayR/config.yml
sed -i "s/t00.test.xyz/t$1.$2/g" /etc/XrayR/config.yml
sed -i "s/s00.test.xyz/s$1.$2/g" /etc/XrayR/config.yml
xrayr restart
xrayr status
